# Generated by Django 5.0.1 on 2024-02-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='status',
        ),
    ]
